version: "3.8"
services:
  ogame-xg-webserver:
    container_name: ogame-xg-webserver
    hostname: ogame-xg-webserver
    build:
      context: .
      args:
        PHP_VERSION: 7.4
    restart: always
    ports:
      - 8888:80
      - 4433:443
    volumes:
      - .:/var/www/html
    depends_on:
      - ogame-xg-db
    networks:
      xg-net:
      nginx-webserver-net:
 
  ogame-xg-db:
    container_name: ogame-xg-db
    hostname: ogame-xg-db
    image: mysql:5.7
    restart: on-failure
    ports:
      - 33060:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: xgp
      MYSQL_ROOT_PASSWORD: root
    networks:
      xg-net:

  ogame-xg-phpmyadmin:
    container_name: ogame-xg-phpmyadmin
    hostname: ogame-xg-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: ogame-xg-db
    networks:
      xg-net:

  ogame-xg-mailhog:
    container_name: ogame-xg-mailhog
    hostname: ogame-xg-mailhog
    image: mailhog/mailhog
    restart: on-failure
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    networks:
      xg-net:

networks:
  nginx-webserver-net:
    name: nginx-net
    external: true
  xg-net:
    name: ogame-xg-net
